#
# build.yml
#

name: Build ARM64 Release

on:
  workflow_dispatch:

jobs:
  build-arm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ARM64 emulation
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up ARM64 build environment
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Run commands inside ARM64 container
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:22.04
          options: |
            --platform=linux/arm64
            -v ${{ github.workspace }}:/workspace
            -w /workspace
          run: |
            apt-get update
            apt-get install -y sudo build-essential file xz-utils
            uname -a
            echo "System info done."
            echo ""
            chmod +x build
            sudo ./build

            echo "Build complete."
            echo ""

      - name: Find generated XZ file
        id: findfile
        run: |
          FILE=$(find . -maxdepth 3 -type f -name "*.xz" | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Verify XZ file exists
        run: |
          if [ -z "${{ steps.findfile.outputs.file }}" ]; then
            echo "No .xz file found!"
            exit 1
          fi

      - name: Upload XZ artifact
        uses: actions/upload-artifact@v5
        with:
          name: arm64-build-${{ github.ref_name }}
          path: ${{ steps.findfile.outputs.file }}
          compression-level: 9
          retention-days: 14


      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ steps.findfile.outputs.file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
